apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbmovie
  labels:
    app: dbmovie
spec:
  selector:
    matchLabels:
      app: dbmovie
  template:
    metadata:
      labels:
        app: dbmovie
    spec:
      containers:
      - name: dbmovie
        image: postgres:18
        env:
          - name: POSTGRES_PASSWORD
            value: mysuperpassword
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: database-env
                key: DB_USER
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: database-env
                key: DB_NAME
        volumeMounts:
          - mountPath: /docker-entrypoint-initdb.d
            name: ddl-init
          - mountPath: /var/lib/postgresql/18/docker
            name: db-data
        ports:
        - containerPort: 5432
      volumes:
        - name: ddl-init
          configMap:
            name: ddl-init
        - name: db-data
          persistentVolumeClaim:
            claimName: db-pvc
