apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  labels:
    app: dbmovie
spec:
  resources:
    requests:
      storage: 2G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
