apiVersion: v1
kind: Service
metadata:
  name: movieservice
spec:
  clusterIP: None # service ClusterIp Headless
  selector:
    app: moviedb
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: moviedb
spec:
  selector:
    matchLabels:
      app: moviedb
  serviceName: movieservice
  replicas: 2
  template:
    metadata:
      labels:
        app: moviedb
    spec:
      containers:
      - name: moviedb
        image: postgres:18
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_PASSWORD
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: database-env
                key: DB_USER
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: database-env
                key: DB_NAME
        volumeMounts:
          - mountPath: /docker-entrypoint-initdb.d
            name: ddl-init
            readOnly: True
          - mountPath: /var/lib/postgresql/18/docker
            name: db-data
      volumes:
        - name: ddl-init
          configMap:
            name: ddl-init
  volumeClaimTemplates:
  - metadata:
      name: db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
