apiVersion: v1
kind: Service
metadata:
  name: movieapi
  labels:
    app: movieapi
spec:
  type: LoadBalancer
  ports:
    - port: 8090
      targetPort: 8080
  selector:
    app: movieapi