apiVersion: apps/v1
kind: Deployment
metadata:
  name: movieapi
  labels:
    app: movieapi
spec:
  selector:
    matchLabels:
      app: movieapi
  replicas: 3
  template:
    metadata:
      labels:
        app: movieapi
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox:1.36
        command:
          - sh
          - -c
          - |
            until nc -z dbmovie 5432; do
              echo "Waiting for database....";
              sleep 2;
            done
      containers:
      - name: movieapi
        image: movieapi:3.0
        env:
          - name: DB_HOST
            value: "dbmovie" # nom du service db (ClusterIp)
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: database-env
                key: DB_NAME
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: database-env
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_PASSWORD
          - name: DB_URL
            value: "postgresql+psycopg2://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
        livenessProbe: # => restart
          httpGet:
            path: /alive
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
        readinessProbe: # => service
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5